name: mdp
channels:
  - defaults
dependencies:
  - matplotlib=3.6.2
  - pip=21.3.1
  - torchvision=0.12.0
  - pytorch=1.11.0
  - ipykernel
  - ipywidgets
  - pip:
    - diffusers=0.10.0
    - Pillow=9.4.0
    - transformers=4.25.1
    - tqdm=4.64.1
